---
- name: Main Playbook
  hosts: my-localhost
  tasks:
    - name: Include ping_google
      import_role:
        name: ping_google
    - name: Include check_up_time
      import_role:
        name: check_up_time
