version: '3'
services:
  metricbeat:
    container_name: metricbeat
    user: root
    image: docker.elastic.co/beats/metricbeat:8.9.2
    restart: always
    command: >
      metricbeat -e
      -E output.elasticsearch.hosts=["localhost:9200"]
      -E output.elasticsearch.username="elastic"
      -E output.elasticsearch.password="changeme"
      --strict.perms=false
    volumes:
      - ./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
