name: Label issue/PR

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Get issue/PR title
        id: get_title
        run: |
          echo "::set-output name=title::$(gh pr view --json title --jq '.title'")

      - name: Check if title matches defined list
        id: check_title
        uses: actions/github-script@v7
        with:
          script: |
            const supportedLabels = ["doc", "jenkins", "enhancement"];
            const title = ${{ steps.get_title.outputs.title }};
            const labels = title.split(/[\s/]+/);

            for (const label of labels) {
              if (!supportedLabels.includes(label)) {
                return "Title does not match supported labels";
              }
            }

            return labels;

      - name: Add labels to issue/PR
        if: ${{ steps.check_title.outputs.result != 'Title does not match supported labels' }}
        uses: actions/github-script@v7
        with:
          script: |
            const labels = ${{ steps.check_title.outputs.result }};

            gh issue add-labels ${{ github.issue.number }} ${labels.join(' ')}
