name: List Folders Workflow
on: push

jobs:
  list_folders_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List folders
        run: |
          cd tools
          ls -la
          chmod +x generate-main-readme.sh
          ./generate-main-readme.sh