name: My First GitHub Action
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: List folders
        run: |
          for d in */; do
            echo "$d"
          done
